#!/bin/sh
# postinst script for opendnssec-conf

set -e

set_perms() {
    if ! dpkg-statoverride --list "$4" >/dev/null; then
        dpkg-statoverride --update --add "$@"
    fi
}

case "$1" in
    configure)

	if ! getent passwd opendnssec > /dev/null; then
            adduser --quiet --system --group --no-create-home --home /var/lib/opendnssec opendnssec
	fi

	set_perms root opendnssec 0750 /etc/opendnssec
	set_perms root opendnssec 0750 /var/lib/opendnssec

	for dir in tmp signconf unsigned signed db; do
	    set_perms opendnssec opendnssec 0755 /var/lib/opendnssec/$dir
	done

	for conf in conf.xml kasp.xml zonefetch.xml zonelist.xml; do
	    ucf /usr/share/opendnssec/$conf /etc/opendnssec/$conf
	    ucfr opendnssec /etc/opendnssec/$conf
	    set_perms root opendnssec 0640 /etc/opendnssec/$conf
	done

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
